ArticleInput:
  type: input-object
  config:
    fields:
      title:
        type: 'String!'
      content:
        type: 'String!'
      author_id:
        type: 'Int!'
      category_id:
        type: 'Int!'